### ISSUE TITLE
Request for a Jar file that can be run with JDK 11

### ISSUE THREAD

**Issue by JLoh579** [SibingWu/duke#5]
@SibingWu  Currently it seems to be compiled with JDK 12, and I can't run it. It's for the peer review, thanks!

**Comment by SibingWu** [comment]
> @SibingWu  Currently it seems to be compiled with JDK 12, and I can't run it. It's for the peer review, thanks!

Hi, I have updated a new jar file. Please kindly have a look~

**Comment by SibingWu** [comment]
> @SibingWu  Currently it seems to be compiled with JDK 12, and I can't run it. It's for the peer review, thanks!

Hi, if you find the jar file successfully compiled, could you please let me know? Thank you so much for your information!!!

**Comment by JLoh579** [comment]
Ok, I’ll let you know as soon as I can! (Im outside, not able to use laptop now)

**Comment by JLoh579** [comment]
> > @SibingWu  Currently it seems to be compiled with JDK 12, and I can't run it. It's for the peer review, thanks!
> 
> Hi, if you find the jar file successfully compiled, could you please let me know? Thank you so much for your information!!!

Yup, I can run the jar file now!
